# Generated by Django 4.0.6 on 2022-07-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number',
        ),
    ]
