# Generated by Django 4.0.6 on 2022-07-30 14:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_remove_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 30, 14, 53, 13, 150179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_rub',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.IntegerField(default=0),
        ),
    ]
