# Generated by Django 4.0.6 on 2022-07-31 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0005_alter_dollar_price_alter_product_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollar',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 31, 9, 28, 45, 28098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='delivery_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 9, 28, 45, 28098, tzinfo=utc)),
        ),
    ]
